#!/usr/bin/env sh
#

set -u -e
exec 2>&1


cd /apps/surferhearts

_bin="bin/surferhearts"
_user="nobody"
_port="81"
echo "=== Starting @ $(date) in ${PWD}: $_bin service run $_port $_user"
exec $_bin service run $_port $_user
